FROM php:8.1.3-cli-alpine
MAINTAINER Norbert Kowalik <norbert.kowalik@icloud.com>

# Installing Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer